---
- name: Ensure Aegir's common dependencies are installed.
  apt:
    name: "{{ item }}"
    state: installed
  with_items: "{{ aegir_dependencies }}"

- name: Ensure Aegir's PHP 5 dependencies are installed.
  apt:
    name: "{{ item }}"
    state: installed
  with_items: "{{ aegir_dependencies_php5 }}"
  when: (aegir_php_version == '5')

- name: Ensure Aegir's PHP 7 dependencies are installed.
  apt:
    name: "{{ item }}"
    state: installed
  with_items: "{{ aegir_dependencies_php7_0 }}"
  when: (aegir_php_version == '7.0')

- name: Ensure Aegir's NGINX dependencies for PHP 5 are installed.
  apt:
    name: "{{ item }}"
    state: installed
  with_items: "{{ aegir_dependencies_nginx_php5 }}"
  when: (aegir_http_service_type == 'nginx') and (aegir_php_version == '5')

- name: Ensure Aegir's NGINX dependencies for PHP 7.0 are installed.
  apt:
    name: "{{ item }}"
    state: installed
  with_items: "{{ aegir_dependencies_nginx_php7_0 }}"
  when: (aegir_http_service_type == 'nginx') and (aegir_php_version == '7.0')

- name: Ensure Aegir's Apache dependencies for PHP 5 are installed.
  apt:
    name: "{{ item }}"
    state: installed
  with_items: "{{ aegir_dependencies_apache_php5 }}"
  when: (aegir_http_service_type == 'apache') and (aegir_php_version == '5')

- name: Ensure Aegir's Apache dependencies for PHP 7.0 are installed.
  apt:
    name: "{{ item }}"
    state: installed
  with_items: "{{ aegir_dependencies_apache_php7_0 }}"
  when: (aegir_http_service_type == 'apache') and (aegir_php_version == '7.0')

