---
# Ref.: https://docs.aegirproject.org/install/#3-configure-system-requirements 
- name: Create 'aegir' group
  group:
    name: "{{ aegir_user }}"
    system: yes

- name: Create 'aegir' user
  user:
    name: "{{ aegir_user }}"
    system: yes
    home: "{{ aegir_root }}"
    group: "{{ aegir_user }}"
    groups: "{{ aegir_web_group }}"
    append: yes

- name: Install Drush
  include: git/drush.yml
  when: aegir_install_drush

  # Ref.: https://docs.aegirproject.org/install/#71-custom-options 
- name: Create 'aegir' user home.
  file:
    path: /var/aegir/
    state: directory
    owner: "{{ aegir_user }}"
    group: "{{ aegir_user }}"

- name: Create ~/.drush/ for 'aegir' user.
  file:
    path: /var/aegir/.drush
    state: directory
    owner: "{{ aegir_user }}"
    group: "{{ aegir_user }}"

# Ref. https://docs.aegirproject.org/install/#43-install-provision
#- name: Clone Provision
#  git:
#    repo: "{{ aegir_provision_repo }}"
#    dest: "{{ aegir_root }}/.drush/provision"
#    depth: 1 # speeds things up
#    version: "{{ aegir_provision_version }}"
#    update: "{{ aegir_provision_update }}"
#  become: yes
#  become_user: "{{ aegir_user }}"

# fast way to download provision
- name: Download Provision
  command: drush dl --destination={{ aegir_root }}/.drush provision-"{{ aegir_provision_version }}" --yes
  become: yes
  become_user: "{{ aegir_user }}"

- include: git/setup-apache.yml
  when: aegir_http_service_type == 'apache'

- include: git/setup-nginx.yml
  when: aegir_http_service_type == 'nginx'

- name: Configure sudo for aegir user
  template:
    src: sudoers_aegir.j2
    dest: "/etc/sudoers.d/{{ aegir_user }}"
    mode: 0440

- name: Clear Drush cache for Provision extension
  command: drush @none cache-clear drush
  become: yes
  become_user: "{{ aegir_user }}"

# Ref.: http://docs.aegirproject.org/en/3.x/install/#44-running-hostmaster-install
- name: Install Aegir front-end
  command: "drush @none --yes hostmaster-install --debug --working-copy --aegir_db_host={{ aegir_db_host | default('localhost') }} --aegir_db_user={{ aegir_db_user }} --aegir_db_pass={{ aegir_db_password }} --aegir_version={{ aegir_platform_version }} --http_service_type={{ aegir_http_service_type }} {{ aegir_frontend_url }} --strict=0 --root={{ aegir_root }}/hostmaster-{{ aegir_platform_version }}/"
  args:
    creates: "{{ aegir_root }}/hostmaster-{{ aegir_platform_version }}/sites/{{ aegir_frontend_url }}/"
  become: yes
  become_user: "{{ aegir_user }}"
