---
- name: Keeping only letters and numbers on platforn name
  set_fact: 
    platform: "{{ item.name | regex_replace('[^A-Za-z0-9]+', '') | replace('.','') }}"

- name: verify if platform exists
  stat:
    path: '{{ aegir_platforms_path }}/{{ platform }}'
  register: check_platform

- name: clone platform
  git:
    repo: "{{ item.repo }}"
    dest: "{{ aegir_platforms_path }}/{{ platform }}"
    version: "{{ item.version }}"
    update: yes
  become: yes
  become_user: "{{ aegir_user }}"

- name: Install dependecies
  composer:
    command: install
    working_dir: "{{ aegir_platforms_path }}/{{ platform }}"
  become: yes
  become_user: "{{ aegir_user }}"

- name: Provision platform
  shell: >
    drush provision-save @platform_{{ platform }} --context_type=platform --root={{ aegir_platforms_path }}/{{ platform }} ;
    drush provision-verify @platform_{{ platform }} ;
    drush @hostmaster hosting-import @platform_{{ platform }}
  become: yes
  become_user: "{{ aegir_user }}"
  args:
    chdir: "{{ aegir_platforms_path }}/{{ platform }}"
  when: not check_platform.stat.exists
